---
- name: Create jail objects
  hosts: localhost
  connection: local
  gather_facts: false

  vars:

    jname: test
    idx_format: "%02i"
    idx_start: 1
    idx_end: 10
    jrange: "{{ range(idx_start | int, idx_end | int + 1) }}"
    jloop_ifc: lo1
    jloop: 127.0.2.0
    jext_ifc: em0
    jext: 10.1.0.50

  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: |
          item: {{ item }}
          name: {{ jname }}_{{ idx_format % (item) }}
          loop_ip: {{ jloop | ansible.utils.ipmath(item) }}
          ext_ip: {{ jext | ansible.utils.ipmath(item) }}
          archive: test_{{ idx_format % (item) }}-firstboot
      loop: "{{ jrange }}"
      when: debug1 | d(false) | bool

    - name: Debug
      ansible.builtin.debug:
        msg: |
          {{ lookup('template', 'jail.yml.j2') }}
      loop: "{{ jrange }}"
      vars:
        jname: test_{{ idx_format % (item) }}
        loop_ip: "{{ jloop | ansible.utils.ipmath(item) }}"
        ext_ip: "{{ jext | ansible.utils.ipmath(item) }}"
        archive: test_{{ idx_format % (item) }}-firstboot
      when: debug2 | d(false) | bool

    - name: Create objects
      when: create_obj | d(false) | bool
      block:
        - name: Create directory
          ansible.builtin.file:
            state: directory
            path: jail.all
            mode: "0755"

        - name: Create objects
          ansible.builtin.template:
            src: jail.yml.j2
            dest: jail.all/{{ name }}.yml
            mode: "0644"
          loop: "{{ jrange }}"
          vars:
            jname: test_{{ idx_format % (item) }}
            loop_ip: "{{ jloop | ansible.utils.ipmath(item) }}"
            ext_ip: "{{ jext | ansible.utils.ipmath(item) }}"
            archive: test_{{ idx_format % (item) }}-firstboot

# EOF
