---

- name: "flavours: Create directories"
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_ezjail_jaildir }}/flavours/{{ item.flavour }}/etc/rc.d"
    mode: "0755"
  loop: "{{ bsd_ezjail_flavours }}"

- name: "flavours: Unarchive files"
  ansible.builtin.unarchive:
    src: "{{ item.archive }}"
    dest: "{{ bsd_ezjail_jaildir }}/flavours/{{ item.flavour }}"
  loop: "{{ bsd_ezjail_flavours }}"
  when: item.archive is defined

- name: "flavours: Synchronize files"
  ansible.posix.synchronize:
    archive: false
    checksum: true
    src: "{{ item.dir }}/"
    dest: "{{ bsd_ezjail_jaildir }}/flavours/{{ item.flavour }}"
  loop: "{{ bsd_ezjail_flavours }}"
  when: item.dir is defined

# EOF
...
