---

- name: "ezjail-conf: Configure {{ bsd_ezjail_conf_file }}"
  template:
    src: ezjail.conf.j2
    dest: "{{ bsd_ezjail_conf_file }}"
    owner: "{{ bsd_ezjail_conf_owner }}"
    group: "{{ bsd_ezjail_conf_group }}"
    mode: "{{ bsd_ezjail_conf_mode }}"
    backup: "{{ bsd_jail_conf_backup }}"
#  notify: restart ezjail

# EOF
...
