---

- name: "ezjail-install: Set ezjail-admin install command"
  ansible.builtin.set_fact:
    install_command: "ezjail-admin {{ bsd_ezjail_install_command }}
                                 {{ bsd_ezjail_install_options }}"

- name: "ezjail-install: Debug. ezjail-admin install command"
  ansible.builtin.debug:
    var: install_command
  when: bsd_jail_debug|bool

- name: "ezjail-install: Run '{{ install_command }}' when bsd_ezjail_install_force"
  ansible.builtin.command:
    cmd: "{{ install_command }}"
  when: bsd_ezjail_install_force|bool

- name: "ezjail-install: Run '{{ install_command }}' when basejail does not exist"
  ansible.builtin.command:
    cmd: "{{ install_command }}"
    creates: "{{ bsd_ezjail_jaildir }}/basejail"

# EOF
...
