---
- name: "Ezjail-conf: Configure {{ bsd_ezjail_conf_file }}"
  notify: restart ezjail
  ansible.builtin.template:
    src: ezjail.conf.j2
    dest: "{{ bsd_ezjail_conf_file }}"
    owner: "{{ bsd_ezjail_conf_owner }}"
    group: "{{ bsd_ezjail_conf_group }}"
    mode: "{{ bsd_ezjail_conf_mode }}"
    backup: "{{ bsd_jail_conf_backup }}"

# TODO (if changed):
# 1) stop jails
# 2) reinstall everything
# 3) start jails

# EOF
