---
- name: "Ezjail-flavours: Create directories"
  tags: bsd_jail_ezjail_flavours_create_dirs
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_ezjail_jaildir }}/flavours/{{ item.flavour }}/etc/rc.d"
    mode: "0775"
  loop: "{{ bsd_ezjail_flavours }}"
  loop_control:
    label: "{{ bsd_ezjail_jaildir }}/flavours/{{ item.flavour }}"

- name: Unarchive files
  tags: bsd_jail_ezjail_flavours_archive
  block:

    - name: "Ezjail-flavours: Unarchive files"
      register: result
      environment:
        CRYPTOGRAPHY_OPENSSL_NO_LEGACY: '1'
      ansible.builtin.unarchive:
        src: "{{ item.archive }}"
        dest: "{{ bsd_ezjail_jaildir }}/flavours/{{ item.flavour }}"
      loop: "{{ bsd_ezjail_flavours | selectattr('archive', 'defined') }}"
      loop_control:
        label: "{{ item.archive }}"

    - name: "Ezjail-flavours: Debug result bsd_jail_debug={{ bsd_jail_debug }}"
      when: bsd_jail_debug | bool
      ansible.builtin.debug:
        var: result

- name: Synchronize files
  tags: bsd_jail_ezjail_flavours_dir
  block:

    - name: "Ezjail-flavours: Synchronize files"
      register: result
      ansible.posix.synchronize:
        src: "{{ item.dir }}/"
        dest: "{{ bsd_ezjail_jaildir }}/flavours/{{ item.flavour }}/"
      loop: "{{ bsd_ezjail_flavours | selectattr('dir', 'defined') }}"
      loop_control:
        label: "{{ item.dir }}"

    - name: "Ezjail-flavours: Debug result bsd_jail_debug={{ bsd_jail_debug }}"
      when: bsd_jail_debug | bool
      ansible.builtin.debug:
        var: result

# EOF
