---

- name: "ezjail-admin: Set ezjail-admin command"
  ansible.builtin.set_fact:
    local_command: "ezjail-admin {{ bsd_ezjail_admin_command }}
                                 {{ bsd_ezjail_admin_options }}"

- name: "ezjail-admin: Debug. ezjail-admin command"
  ansible.builtin.debug:
    var: local_command
  when: bsd_jail_debug|bool

- name: "ezjail-admin: Run {{ local_command }} when bsd_ezjail_admin_force"
  command:
    cmd: "{{ local_command }}"
  when: bsd_ezjail_admin_force|bool

- name: "ezjail-admin: Run {{ local_command }} when basejail does not exist"
  command:
    cmd: "{{ local_command }}"
    creates: "{{ bsd_ezjail_jaildir }}/basejail"

# EOF
...
