---

- name: "ezjail-flavours: Create directories"
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_ezjail_jaildir }}/flavours/{{ item.flavour }}/etc/rc.d"
    mode: '0755'
  loop: "{{ bsd_ezjail_flavours }}"
  tags: bsd_jail_ezjail_flavours_create_dirs

- name: "ezjail-flavours: Unarchive files"
  ansible.builtin.unarchive:
    src: "{{ item.archive }}"
    dest: "{{ bsd_ezjail_jaildir }}/flavours/{{ item.flavour }}"
  loop: "{{ bsd_ezjail_flavours }}"
  register: result
  when: item.archive is defined
  tags: bsd_jail_ezjail_flavours_archive

- name: "ezjail-flavours: Synchronize files"
  ansible.posix.synchronize:
    src: "{{ item.dir }}/"
    dest: "{{ bsd_ezjail_jaildir }}/flavours/{{ item.flavour }}/"
  loop: "{{ bsd_ezjail_flavours }}"
  register: result
  when: item.dir is defined

- name: "ezjail-flavours: Debug result"
  ansible.builtin.debug:
    var: result
  when: bsd_jail_debug|bool
  tags: bsd_jail_ezjail_flavours_dir

# EOF
...
