---

- name: "firstboot: Create stamp dir {{ bsd_jail_stamp_dir }}"
  file:
    state: "directory"
    path: "{{ bsd_jail_stamp_dir }}"

- name: "firstboot: Exec firstboot scripts in the jails"
  include_tasks: fn/firstboot-jail.yml
  loop: "{{ bsd_jail_jails }}"
  when:
    - bsd_jail_enable|bool
    - item.present|default(true)
    - item.start
    - item.firstboot is defined

# EOF
...
