---

- name: "firstboot: Create stamp dir {{ bsd_jail_stamp_dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_jail_stamp_dir }}"
    mode: "0755"

- name: "firstboot: Exec firstboot scripts in the jails"
  ansible.builtin.include_tasks: fn/firstboot-jail.yml
  loop: "{{ bsd_jail_jails }}"
  loop_control:
    label: "{{ item.jailname }}"
  when:
    - bsd_jail_enable|bool
    - item.present|default(true)
    - item.start|default(true)
    - item.firstboot is defined

# EOF
...
