---
- name: "Fstab: Create directory {{ bsd_jail_fstab_dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ bsd_jail_fstab_dir }}"
    mode: "0755"

- name: "Fstab: Delete fstab files in {{ bsd_jail_fstab_dir }}"
  ansible.builtin.file:
    state: absent
    path: "{{ bsd_jail_fstab_dir }}/fstab.{{ item.jailname }}"
  loop: "{{ bsd_jail_jails }}"
  loop_control:
    label: "{{ bsd_jail_fstab_dir }}/fstab.{{ item.jailname }}"
  when: not item.present | d(true)

- name: "Fstab: Create fstab files in {{ bsd_jail_fstab_dir }}"
  ansible.builtin.template:
    src: fstab.j2
    dest: "{{ bsd_jail_fstab_dir }}/fstab.{{ item.jailname }}"
    owner: "{{ bsd_jail_conf_owner }}"
    group: "{{ bsd_jail_conf_group }}"
    mode: "{{ bsd_jail_conf_mode }}"
  loop: "{{ bsd_jail_jails }}"
  loop_control:
    label: "{{ bsd_jail_fstab_dir }}/fstab.{{ item.jailname }}"
  when: item.present | d(true)

# EOF
