---

- name: "jail-conf: Configure {{ bsd_jail_conf_file }}"
  template:
    src: jail.conf.j2
    dest: "{{ bsd_jail_conf_file }}"
    owner: "{{ bsd_jail_conf_owner }}"
    group: "{{ bsd_jail_conf_group }}"
    mode: "{{ bsd_jail_conf_mode }}"
    backup: "{{ bsd_jail_conf_backup }}"
#  notify: restart jail

# EOF
...
