---
# tasks freebsd_jail

- name: Import vars.yml
  ansible.builtin.import_tasks: vars.yml
  tags: [always, bsd_jail_vars]

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: bsd_jail_debug|bool
  tags: [always, bsd_jail_debug]

- name: Include vbotka.freebsd_postinstall mount-iso
  ansible.builtin.include_role:
    name: vbotka.freebsd_postinstall
    tasks_from: mount-iso.yml
  when: bsd_jail_mount_iso|bool
  tags: bsd_jail_mount_iso

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  when: bsd_jail_assert|bool
  tags: bsd_jail_assert

- name: Import packages.yml
  ansible.builtin.import_tasks: packages.yml
  when: bsd_jail_install|bool
  tags: bsd_jail_packages

- name: Import fstab.yml
  ansible.builtin.import_tasks: fstab.yml
  tags: bsd_jail_fstab

- name: Import jail-conf.yml
  ansible.builtin.import_tasks: jail-conf.yml
  when: bsd_jail|bool
  tags: bsd_jail_jail_conf

- name: Import jail-rcconf.yml
  ansible.builtin.import_tasks: jail-rcconf.yml
  when: bsd_jail|bool
  tags: bsd_jail_jail_rcconf

- name: Import ezjail-flavours.yml
  ansible.builtin.import_tasks: ezjail-flavours.yml
  when: bsd_ezjail|bool
  tags: bsd_jail_flavours

- name: Import ezjail-conf.yml
  ansible.builtin.import_tasks: ezjail-conf.yml
  when: bsd_ezjail|bool
  tags: bsd_jail_ezjail_conf

- name: Import ezjail-jails.yml
  ansible.builtin.import_tasks: ezjail-jails.yml
  when: bsd_ezjail|bool
  tags: bsd_jail_ezjail_jails

- name: Import ezjail-rcconf.yml
  ansible.builtin.import_tasks: ezjail-rcconf.yml
  when: bsd_ezjail|bool
  tags: bsd_jail_ezjail_rcconf

- name: Meta flush_handlers
  ansible.builtin.meta: flush_handlers

- name: Import ezjail-admin.yml
  ansible.builtin.import_tasks: ezjail-admin.yml
  when: bsd_ezjail|bool
  tags: bsd_jail_ezjail_admin

- name: Import start.yml
  ansible.builtin.import_tasks: start.yml
  when: bsd_jail_start|bool
  tags: bsd_jail_start

- name: Import firstboot.yml
  ansible.builtin.import_tasks: firstboot.yml
  when: bsd_jail_firstboot|bool
  tags: bsd_jail_firstboot

# EOF
...
