---

- name: "packages: Install packages"
  pkgng:
    name: "{{ bsd_jail_packages }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_jail_packages }}"
  when: freebsd_install_method == "ports"

- name: "packages: Install extra packages"
  pkgng:
    name: "{{ bsd_jail_packages_extra }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install extra ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_jail_packages_extra }}"
  when: freebsd_install_method == "ports"

# EOF
...
