---
- name: "Pkg: Install packages"
  when: freebsd_install_method | lower == 'packages'
  register: result
  community.general.pkgng:
    name: "{{ bsd_jail_packages }}"
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"

- name: "Pkg: Install ports"
  when: freebsd_install_method | lower == 'ports'
  register: result
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages | d(true) }}"
  loop: "{{ bsd_jail_packages }}"
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"

- name: "Pkg: Install extra packages"
  when: freebsd_install_method | lower == 'packages'
  register: result
  community.general.pkgng:
    name: "{{ bsd_jail_packages_extra }}"
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"

- name: "Pkg: Install extra ports"
  when: freebsd_install_method | lower == 'ports'
  register: result
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_jail_packages_extra }}"
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"

# EOF
