---
- name: "Start: Assert bsd_jail_id is defined"
  ansible.builtin.assert:
    that: bsd_jail_id is defined
    fail_msg: The variable bsd_jail_id is missing. Run tag bsd_jail_ezjail_info.

- name: Start/Stop jails
  when: bsd_ezjail_enable | bool
  block:

    - name: "Start: Stop jails"
      ansible.builtin.command:
        cmd: /usr/local/bin/ezjail-admin stop {{ item.jailname }}
        removes: "{{ bsd_jail_id_dir }}/jail_{{ item.jailname }}.id"
      loop: "{{ bsd_jail_jails_present }}"
      loop_control:
        label: "{{ item.jailname }}"
      when: not item.start | d(true)

    - name: "Start: Start jails"
      ansible.builtin.command:
        cmd: /usr/local/bin/ezjail-admin start {{ item.jailname }}
        creates: "{{ bsd_jail_id_dir }}/jail_{{ item.jailname }}.id"
      loop: "{{ bsd_jail_jails_present }}"
      loop_control:
        label: "{{ item.jailname }}"
      when:
        - item.start | d(true)
        - item.jailname not in bsd_jail_id

# TODO: Restart restored jails
#    - name: "start: Restart jails with ezjail"
#      ansible.builtin.command:
#        cmd: "/usr/local/bin/ezjail-admin restart {{ item }}"
#      loop: "{{ bsd_ezjail_restart_jails }}"

# EOF
