---

- name: "start: Stop jails"
  command: "/etc/rc.d/jail stop {{ item.jailname }}"
  args:
    removes: "{{ bsd_jail_id_dir }}/jail_{{ item.jailname }}{{ '.' }}id"
  loop: "{{ bsd_jail_jails }}"
  when:
    - bsd_jail_enable
    - item.present|default('true')
    - not item.start

- name: "start: Start jails"
  command: "/etc/rc.d/jail start {{ item.jailname }}"
  args:
    creates: "{{ bsd_jail_id_dir }}/jail_{{ item.jailname }}{{ '.' }}id"
  loop: "{{ bsd_jail_jails }}"
  when:
    - bsd_jail_enable
    - item.present|default('true')
    - item.start

# EOF
...
