---

- block:

    - name: "start: Start and Stop jails"
      ansible.builtin.command:
        cmd: "/usr/local/bin/ezjail-admin stop {{ item.jailname }}"
        removes: "{{ bsd_jail_id_dir }}/jail_{{ item.jailname }}.id"
      loop: "{{ bsd_jail_jails_present }}"
      loop_control:
        label: "{{ item.jailname }} {{ action }}"
      vars:
        action: "{{ item.start|default(true)|ternary('start', 'stop') }}"
      changed_when: false

# TODO: Restart restored jails
#    - name: "start: Restart jails with ezjail"
#      ansible.builtin.command:
#        cmd: "/usr/local/bin/ezjail-admin restart {{ item }}"
#      loop: "{{ bsd_ezjail_restart_jails }}"

  when: bsd_ezjail_enable|bool

# EOF
...
