---
# handlers freebsd_jail

# ezjail

- name: Enable and start ezjail
  listen: enable and start ezjail
  ansible.builtin.service:
    name: "{{ bsd_ezjail_service }}"
    state: started
    enabled: true

- name: Disable and stop ezjail
  listen: disable and stop ezjail
  ansible.builtin.service:
    name: "{{ bsd_ezjail_service }}"
    state: stopped
    enabled: false

- name: Start ezjail
  listen: start ezjail
  ansible.builtin.service:
    name: "{{ bsd_ezjail_service }}"
    state: started

- name: Stop ezjail
  listen: stop ezjail
  ansible.builtin.service:
    name: "{{ bsd_ezjail_service }}"
    state: stopped

- name: Restart ezjail
  listen: restart ezjail
  ansible.builtin.service:
    name: "{{ bsd_ezjail_service }}"
    state: restarted
  when: bsd_ezjail_enable | bool

# jail

- name: Enable and start jail
  listen: enable and start jail
  ansible.builtin.service:
    name: "{{ bsd_jail_service }}"
    state: started
    enabled: true

- name: Disable and stop jail
  listen: disable and stop jail
  ansible.builtin.service:
    name: "{{ bsd_jail_service }}"
    state: stopped
    enabled: false

- name: Start jail
  listen: start jail
  ansible.builtin.service:
    name: "{{ bsd_jail_service }}"
    state: started

- name: Stop jail
  listen: stop jail
  ansible.builtin.service:
    name: "{{ bsd_jail_service }}"
    state: stopped

- name: Restart jail
  listen: restart jail
  ansible.builtin.service:
    name: "{{ bsd_jail_service }}"
    state: restarted
  when: bsd_jail_enable | bool

# EOF
