---

- name: "ezjail-jails:delete: Debug {{ item.jailname }}"
  vars:
    msg: |
         item.jailname [{{ item.jailname }}]
         bsd_jail_id_dir [{{ bsd_jail_id_dir }}]
         bsd_ezjail_jaildir [{{ bsd_ezjail_jaildir }}]
         bsd_jail_stamp_dir [{{ bsd_jail_stamp_dir }}]
         id_file [{{ bsd_jail_id_dir }}/jail_{{ item.jailname }}{{ '.' }}id]
         stamp_file [{{ bsd_jail_stamp_dir }}/{{ item.jailname }}-firstboot]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: bsd_jail_debug|bool

- name: "ezjail-jails:delete: Stop jail {{ item.jailname }}"
  command: "/etc/rc.d/jail stop {{ item.jailname }}"
  args:
    removes: "{{ bsd_jail_id_dir }}/jail_{{ item.jailname }}{{ '.' }}id"
  when: bsd_jail_enable|bool

- name: "ezjail-jails:delete: Delete jail {{ item.jailname }}"
  command: "ezjail-admin delete -wf {{ item.jailname }}"
  args:
    removes: "{{ bsd_ezjail_jaildir }}/{{ item.jailname }}"

- name: "ezjail-jails:delete: Delete stamp {{ stamp_file }}"
  file:
    state: absent
    path: "{{ stamp_file }}"
  vars:
    stamp_file: "{{ bsd_jail_stamp_dir }}/{{ item.jailname }}-firstboot"

# EOF
...
