---
- name: "Firstboot: Create path to stamp file for {{ item.jailname }}"
  ansible.builtin.set_fact:
    stamp_file: "{{ bsd_jail_stamp_dir }}/{{ item.jailname }}-firstboot"

- name: "Firstboot: Stat stamp file for {{ item.jailname }}"
  register: stamp_file_stat
  ansible.builtin.stat:
    path: "{{ stamp_file }}"

- name: "Firstboot: Debug stat {{ stamp_file }}"
  when: bsd_jail_debug | bool
  ansible.builtin.debug:
    var: stamp_file_stat.stat.exists

- name: Execute firstboot script
  when: not stamp_file_stat.stat.exists
  block:

    - name: "Firstboot: chown firstboot script in {{ item.jailname }}"
      register: result
      ansible.builtin.command: # noqa: no-changed-when
        cmd: >
          /usr/local/bin/ezjail-admin console
          -f -e 'chown {{ item.firstboot_owner | d('root') }}:{{ item.firstboot_group | d('wheel') }}
          {{ item.firstboot }}' {{ item.jailname }}

    - name: "Firstboot: Debug result chown firstboot {{ item.jailname }}"
      when: bsd_jail_debug | bool
      ansible.builtin.debug:
        var: result

    - name: "Firstboot: chmod firstboot script in {{ item.jailname }}"
      register: result
      ansible.builtin.command: # noqa: no-changed-when
        cmd: >
          /usr/local/bin/ezjail-admin console
          -e 'chmod {{ item.firstboot_mode | d('0755') }}
          {{ item.firstboot }}' {{ item.jailname }}

    - name: "Firstboot: Debug result chmod firstboot {{ item.jailname }}"
      when: bsd_jail_debug | bool
      ansible.builtin.debug:
        var: result

    - name: "Firstboot: Execute firstboot script in {{ item.jailname }}"
      register: result
      ansible.builtin.shell: # noqa: no-changed-when
        cmd: >
          /usr/local/bin/ezjail-admin console
          -e {{ item.firstboot }} {{ item.jailname }} &&
          /usr/bin/touch {{ stamp_file }}

    - name: "Firstboot: Debug result firstboot {{ item.jailname }}"
      when: bsd_jail_debug | bool
      ansible.builtin.debug:
        var: result

# EOF
