---

- name: "ezjail-jails:objects: Include vars from {{ item }}"
  include_vars: "{{ item }}"

- name: "ezjail-jails:objects: Add {{ item }} to bsd_jail_jails"
  ansible.builtin.set_fact:
    bsd_jail_jails: "{{ bsd_jail_jails + objects }}"

# EOF
...
